version: '3.8'
services:
  node:
    image: 'node:16-alpine'
    user: 'node'
    working_dir: '/app'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    expose:
      - '3700'
    ports:
      - '3700:3700'
    command: 'npm start'